"""Add calendar model

Revision ID: f7ca2474fc1c
Revises: 496c25993acb
Create Date: 2024-09-10 14:40:28.805089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ca2474fc1c'
down_revision = '496c25993acb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_title', ['title'], unique=False)

    # ### end Alembic commands ###
